### ISSUE TITLE
Excess terminal output

### ISSUE THREAD

**Issue by ygcool** [FindoraNetwork/findora-sdk#113]
```
const balanceAlso = await AccountApi.getBalance(walletInfo);
console.log(balanceAlso);
```

cli:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/16422689/157784843-1291d384-561c-47cd-bbc3-edb5b52f7ca4.png">

Why is there a number being printed?

**Comment by okovalov** [comment]
@ygcool it was there just for information purposes
