### ISSUE TITLE
The hash returned from sending a transaction cannot be queried in the block explorer

### ISSUE THREAD

**Issue by ygcool** [FindoraNetwork/findora-sdk#114]
[send example](https://github.com/FindoraNetwork/findora-sdk-examples/blob/311ed19f09f89bc5a9eda1bdd3d9de00da3a8f8c/index.js#L57)

The hash returned from sending a transaction cannot be queried in the block explorer

testnet send transaction return:
44d8c650a8b962b40e3d3fd180872232b77e5e8be42614cf106fd1d2ed15f1c5

The correct transaction hash is:
EAEE3E46C5425A01D4A7EF994ADA4179AA3981480B1C0E0823A33CB8C982B90E

block explorer:
https://prod-testnet.findorascan.io

**Comment by okovalov** [comment]
@ygcool yes, those are two different things. after submitting the transaction you get `44d8c650a8b962b40e3d3fd180872232b77e5e8be42614cf106fd1d2ed15f1c5`. Then, to see the tx details you need to queue a query service, which would return a tx details and within the details you will see `EAEE3E46C5425A01D4A7EF994ADA4179AA3981480B1C0E0823A33CB8C982B90E` 

please refer to this example

![CleanShot 2022-08-27 at 18 54 57](https://user-images.githubusercontent.com/1706749/187050727-0e7bf0b2-6996-4163-aa6e-f750b5429130.png)

when you run it, you will see smth like 

![CleanShot 2022-08-27 at 18 54 27](https://user-images.githubusercontent.com/1706749/187050746-37eb58e5-a3b5-4e65-93e2-7c549484ebca.png)
