### ISSUE TITLE
erc distribution json required client file 

### ISSUE THREAD

**Issue by ChaoticFindorian** [FindoraNetwork/findora-sdk#147]
{
  "rpc": {
    "rpcUrl": "http://127.0.0.1:8545",
    "mnemonic1": "image crater carbon property trumpet assault satoshi helmet bulb tiny upgrade minimum foil search fluid cement clever hello wrap night poverty floor addict scene"
  }
}

**Comment by okovalov** [comment]
fixed here https://github.com/FindoraNetwork/findora-sdk/pull/149 @ChaoticFindorian @ws4charlie
