### ISSUE TITLE
sendToMany

### ISSUE THREAD

**Issue by patrickmogul** [FindoraNetwork/findora-sdk#188]
Hello!

After the recent update sendToAddress is working fine if I throttle it down to 1 transaction per block, looping every 16.5 seconds. I tried this on the main https://rpc-mainnet.findora.org and directly with my validator and had similar results with each so I don't think I was being limited by the rpc it just wouldn't handle more than 1 tx at a time.

So I attempted to swap over to using sendToMany with a list of my 41 tx instead but I am running into the following issue:

![image](https://user-images.githubusercontent.com/6798465/213784008-6a57b859-e367-4f5e-8f54-3d271617acad.png)

I've verified the sending wallet is good, my array of info containing the [ { reciversWalletInfo, amount } ] are formatted correctly, and my other options are good but I get the attached error from wasm-js-bindings (including a little bit of my wallet/sending info for an example of the formatting of that being passed in). 

It's failing on this piece of my code, walletInfo is the same that works on my sendToAddress and queTransactions is my data containing reciversWalletInfo and amount:

```
const transactionBuilder = await TransactionApi.sendToMany(
        walletInfo,
        queTransactions,
        assetCode,
        assetBlindRulesForSend
    );
```

Issues:
1. sendToAddress - only 1 tx per block works, remainder fail, throttling tx to move at blockchain speed works to send all tx.
2. sendToMany - The error in the photo happens when running my code above in findora-wallet-wasm

I dug into sendToMany in the sdk and see that `reciversWalletInfo` is indeed what is being checked, but I think the spelling of this item may be incorrect and it should be `receiversWalletInfo` - I went with it as is as the docs has it as `reciversWalletInfo` as well.

**Comment by patrickmogul** [comment]
No problem, I will attempt to run in batches of 5 recipients and step up slightly if that works, thanks!

**Comment by okovalov** [comment]
@patrickmogul @ws4charlie @HelloRickey  guys, I can confirm that both `sendToAddress` and `sendToMany` works as for now.
I have tried both methods, and both seem to be working fine. Balances are properly changed for both sender and receivers.

Here are a few tx I sent a few minutes ago

Using `sendToMany`

https://findorascan.io/tx/f741586d125e2a4975e935dbca6d04d6e01870dbedd33f8c82db82a08ee75fed
https://findorascan.io/tx/dde99a220b226646db510bed0b6d4089779f87308e682a7155ff286c5da2143a

Using `sendToAddress`

https://findorascan.io/tx/e125173b578a0324bc29a882af4fddae30532a4b8b67be37e76a2573a20f4de7

Just in case, here is an example of the implementation 

```ts

const recieversInfo = [
    { reciverWalletInfo: toWalletInfoMine1, amount: '0.21' },
    { reciverWalletInfo: toWalletInfoMine2, amount: '0.22' },
    { reciverWalletInfo: toWalletInfoMine3, amount: '0.23' },
  ];

  const transactionBuilder = await Transaction.sendToMany(
    walletInfo,
    recieversInfo,
    assetCode,
    assetBlindRules,
  );

  const resultHandle = await Transaction.submitTransaction(transactionBuilder);

// single one
const transactionBuilder = await Transaction.sendToAddress(
    walletInfo,
    toWalletInfo.address,
    '0.25',
    assetCode,
    assetBlindRules,
  );

  const resultHandle = await Transaction.submitTransaction(transactionBuilder);
```
I hope it helps. Please let me know if you have any other questions, will do my best to help :)
