### ISSUE TITLE
Installing dependencies 

### ISSUE THREAD

**Issue by binsta** [FindoraNetwork/findora-sdk#90]
node -v

```
v16.13.1
```
npm -v
```
8.1.2
```
yarn add @findora-network/findora-sdk.js

```error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/FindoraNetwork/wasm-js-bindings.git
Directory: home/test-lib
Output:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by okovalov** [comment]
@binsta we have published a new release of the `Findora SDK` , which should have this problem fixed. Please check out version **1.1.0**  and let me know how it goes. 

https://www.npmjs.com/package/@findora-network/findora-sdk.js

thank you!
